### Cse-221710309059-v praveenkumar

In [1]:
#answer: 1



import numpy as np
s = np.arange(8, 18)
print("Original array:")
print(s)
print("Reverse array:")
s = s[::-1]
print(s)

Original array:
[ 8  9 10 11 12 13 14 15 16 17]
Reverse array:
[17 16 15 14 13 12 11 10  9  8]


In [2]:
#answer 2


import numpy as np
s = np.ones((6,6))
print("Original array:")
print(s)
print("1 on the border and 0 inside in the array")
s[1:-1,1:-1] = 0
print(s)

Original array:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [3]:
#answer 3


import numpy as np
arr1 = np.array([8, 10, 18, 23, 31])
print("Array1: ",arr1)
arr2 = [8, 31]
print("Array2: ",arr2)
print("Compare each element of array1 and array2")
print(np.in1d(arr1, arr2))

Array1:  [ 8 10 18 23 31]
Array2:  [8, 31]
Compare each element of array1 and array2
[ True False False False  True]


In [4]:
 #answer 4
    
import numpy as np
arr3 = np.array([10, 18, 23, 38, 49, 60])
print("Array1: ",arr3)
arr4 = [10, 23, 31, 42, 49]
print("Array2: ",arr4)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(arr3, arr4))

Array1:  [10 18 23 38 49 60]
Array2:  [10, 23, 31, 42, 49]
Unique values in array1 that are not in array2:
[18 38 60]


In [5]:
#answer 5

import numpy as np
s =  np.diagflat([4, 5, 6, 8])
print(s)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
